Refactor package names and update default configuration

diff --git a/scripts/install.sh.tmpl b/scripts/install.sh.tmpl
--- a/scripts/install.sh.tmpl
+++ b/scripts/install.sh.tmpl
@@ -2,7 +2,7 @@
 if [ "$DEBUG" == "1" ]; then
 	set -x
 fi
-TMP_DIR=$(mktemp -d -t jpillora-installer-XXXXXXXXXX)
+TMP_DIR=$(mktemp -d -t installer-XXXXXXXXXX)
 function cleanup {
 	rm -rf $TMP_DIR > /dev/null
 }
@@ -12,7 +12,25 @@ function fail {
 	echo "============"
 	echo "Error: $msg" 1>&2
 	exit 1
+}	
+function move {
+	#move into PATH or cwd
+	chmod +x $1 || fail "chmod +x failed"
+	#move without sudo
+	OUT=$(mv $1 $2 2>&1)
+	STATUS=$?
+	# failed and string contains "Permission denied"
+	if [ $STATUS -ne 0 ]; then
+		if [[ $OUT =~ "Permission denied" ]]; then
+			echo "mv with sudo..."
+			sudo mv $1 $2 || fail "sudo mv failed" 
+		else
+			fail "mv failed ($OUT)"
+		fi
+	fi
+	echo "{{ if .MoveToPath }}Installed at{{ else }}Downloaded to{{ end }} $2"     
 }
+
 function install {
 	#settings
 	USER="{{ .User }}"
@@ -135,36 +153,30 @@ function install {
 	else
 		fail "unknown file type: $FTYPE"
 	fi
-	#search subtree largest file (bin)
-	TMP_BIN=$(find . -type f | xargs du | sort -n | tail -n 1 | cut -f 2)
-	if [ ! -f "$TMP_BIN" ]; then
-		fail "could not find find binary (largest file)"
-	fi
-	#ensure its larger than 1MB
-	#TODO linux=elf/darwin=macho file detection?
-	if [[ $(du -m $TMP_BIN | cut -f1) -lt 1 ]]; then
-		fail "no binary found ($TMP_BIN is not larger than 1MB)"
-	fi
-	#move into PATH or cwd
-	chmod +x $TMP_BIN || fail "chmod +x failed"
-	DEST="$OUT_DIR/$PROG"	
+
 	if [ ! -z "$ASPROG" ]; then
 		DEST="$OUT_DIR/$ASPROG"
-	fi
-	#move without sudo
-	OUT=$(mv $TMP_BIN $DEST 2>&1)
-	STATUS=$?
-	# failed and string contains "Permission denied"
-	if [ $STATUS -ne 0 ]; then
-		if [[ $OUT =~ "Permission denied" ]]; then
-			echo "mv with sudo..."
-			sudo mv $TMP_BIN $DEST || fail "sudo mv failed" 
+		TMP_BIN=$(find . -type f -name "*$ASPROG*" | head -n 1 | cut -f 2)
+		if [ ! -f "$TMP_BIN" ]; then
+		fail "could not find binary"
+		fi
+		move $TMP_BIN $DEST
+	else
+		TMP_BIN_DIR=$(find . -type d -name "*bin*" | head -n 1 | cut -f 2)
+		if [ ! -d "$TMP_BIN_DIR" ]; then
+		   TMP_BIN=$(find . -type f | xargs du | sort -n | tail -n 1 | cut -f 2)
+		   if [ ! -f "$TMP_BIN" ]; then
+		   fail "could not find find binary (largest file)"
+		   fi
+		   move $TMP_BIN $OUT_DIR/$(basename $TMP_BIN)
 		else
-			fail "mv failed ($OUT)"
+		   for f in $TMP_BIN_DIR/*; do
+			   if [ -x "$f" ]; then
+				   move $f $OUT_DIR/$(basename $f)
+			   fi
+		   done
 		fi
 	fi
-	echo "{{ if .MoveToPath }}Installed at{{ else }}Downloaded to{{ end }} $DEST"
-	#done
 	cleanup
 }
 install
